/**
 * Request and response shapes for the Meshgate Trust Layer API.
 *
 * These types match the wire protocol exactly. See PROTOCOL.md for the
 * full HTTP specification including retry logic, error codes, and
 * security constraints.
 */

// ─── POST /v1/intent ─────────────────────────────────────────────────────────

/** Request body for POST /v1/intent */
export interface IntentRequest {
  /** The intent name for policy evaluation. */
  intent: string;
  /**
   * Flat record of intent arguments for policy evaluation.
   * All values must be string | number | boolean.
   * Omit or pass `{}` if the policy only needs the intent name.
   */
  intentArgs?: Record<string, string | number | boolean>;
  /**
   * base64(SHA-256(JSON.stringify(args))) — one-way hash of function args.
   * Sent to cloud for tamper detection on verify-token. Cloud never receives
   * plaintext args.
   */
  payloadHash: string;
  /**
   * 32-byte random value, base64url-encoded. Generated by the SDK before this
   * call. Used as the HKDF salt for AES key derivation. Stored in the cloud;
   * returned on verify-token. Never stored locally (split-knowledge property).
   */
  gateNonce: string;
  /**
   * Gate expiry TTL in seconds. Range: 60–604800.
   * If omitted, the cloud uses the configured tenant/agent/intent TTL.
   */
  expiresInSeconds?: number;
  /**
   * Human-readable description shown in the Meshgate dashboard.
   * Max 1000 characters.
   */
  description?: string;
}

/**
 * Response from POST /v1/intent.
 *
 * Three possible outcomes:
 * - `allowed` (HTTP 200): policy allows immediate execution — call fn() now
 * - `gated` (HTTP 201): policy requires human approval — enter gate flow
 * - `blocked` (HTTP 403): policy blocks this intent — throw MeshgateBlockedError
 */
export type IntentResponse =
  | {
      outcome: 'allowed';
      intent: string;
      /** The policy rule that matched and allowed this intent. */
      matchedPolicy: unknown;
    }
  | {
      outcome: 'gated';
      /** Meshgate approval ID — used as the storage key and SSE filter. */
      approvalId: string;
      intent: string;
      /** ISO-8601 expiry timestamp for this gate. */
      expiresAt: string;
    }
  | {
      outcome: 'blocked';
      /** Machine-readable error code, e.g. `'intent_blocked'`. */
      error: string;
      intent: string;
      /** The policy rule that matched and blocked this intent. */
      matchedPolicy: unknown;
    };

// ─── GET /v1/approvals/:id/status ────────────────────────────────────────────

/**
 * Response from GET /v1/approvals/:id/status.
 *
 * Used as the polling fallback when SSE is unavailable, and by `reconcile()`
 * on startup to check the current state of pending gates.
 */
export interface ApprovalStatusResponse {
  /** The approval ID. */
  id: string;
  /** Current approval lifecycle state. */
  status: 'pending' | 'approved' | 'rejected' | 'expired';
  /** ISO-8601 timestamp of when the gate was resolved. Null if still pending. */
  resolvedAt: string | null;
  /**
   * One-time token for the verify-token call.
   * Present only when `status === 'approved'` and not yet burned.
   * Null if pending, rejected, expired, or already consumed.
   */
  token: string | null;
  /**
   * The gateNonce for this approval (used to re-derive the HKDF key).
   * Present only when `status === 'approved'`.
   * Null otherwise.
   */
  gateNonce: string | null;
}

// ─── External Approval Requests ─────────────────────────────────────────────

export type ExternalApprovalStatus = 'pending' | 'approved' | 'rejected' | 'expired' | 'cancelled';
export type ExternalApprovalTerminalStatus = Exclude<ExternalApprovalStatus, 'pending'>;
export type ExternalApprovalRiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type ExternalApprovalResumeMode = 'poll' | 'events';
export type ExternalApprovalRoleHint = 'viewer' | 'operator' | 'admin';

export type ExternalApprovalEvidenceType =
  | 'policy_decision'
  | 'risk_signal'
  | 'tool_arguments'
  | 'runtime_trace'
  | 'human_note';

export type ExternalApprovalEvidenceOutcome =
  | 'allowed'
  | 'gated'
  | 'blocked'
  | 'flagged'
  | 'informational';

export type ExternalApprovalRedactionState =
  | 'none'
  | 'summary_only'
  | 'redacted'
  | 'external_ref_only';

export interface ExternalApprovalEvidenceInput {
  evidenceType: ExternalApprovalEvidenceType;
  label: string;
  summary: string;
  outcome?: ExternalApprovalEvidenceOutcome;
  riskLevel?: ExternalApprovalRiskLevel;
  policyId?: string;
  ruleId?: string;
  traceId?: string;
  payloadJson?: Record<string, unknown> | null;
  payloadRef?: string;
  redactionState?: ExternalApprovalRedactionState;
}

export interface ExternalApprovalRequestInput {
  agentId?: string;
  sourceSystem: string;
  externalRequestId?: string;
  actionName: string;
  actionSummary: string;
  payloadSummary?: string;
  payloadRef?: string;
  policyEngine?: string;
  policyId?: string;
  ruleId?: string;
  riskLevel?: ExternalApprovalRiskLevel;
  requestedTeamId?: string;
  requestedRole?: ExternalApprovalRoleHint;
  resumeMode?: ExternalApprovalResumeMode;
  expiresAt?: string;
  expiresInSeconds?: number;
  idempotencyKey: string;
  evidence?: ExternalApprovalEvidenceInput[];
}

export interface ExternalApprovalEvidenceAppendInput extends ExternalApprovalEvidenceInput {
  idempotencyKey: string;
}

export interface ExternalApprovalDecision {
  outcome: ExternalApprovalTerminalStatus;
  resolvedAt: string | null;
  note: string | null;
}

export interface ExternalApprovalEvidence {
  id: string;
  evidenceType: ExternalApprovalEvidenceType;
  label: string;
  summary: string;
  outcome: ExternalApprovalEvidenceOutcome | null;
  riskLevel: ExternalApprovalRiskLevel | null;
  policyId: string | null;
  ruleId: string | null;
  traceId: string | null;
  payloadJson?: Record<string, unknown> | null;
  payloadRef: string | null;
  redactionState: ExternalApprovalRedactionState;
  createdAt: string;
}

export interface ExternalApprovalEventFilter {
  entityType: 'approval';
  entityId: string;
  eventTypes: Array<'approval.approved' | 'approval.rejected' | 'approval.expired'>;
}

export interface ExternalApprovalStatusResponse {
  approvalId: string;
  status: ExternalApprovalStatus;
  sourceSystem: string;
  externalRequestId: string | null;
  actionName: string;
  actionSummary: string;
  payloadSummary: string | null;
  payloadRef: string | null;
  policyEngine: string | null;
  policyId: string | null;
  ruleId: string | null;
  riskLevel: ExternalApprovalRiskLevel | null;
  resumeMode: ExternalApprovalResumeMode;
  eventFilter: ExternalApprovalEventFilter;
  decision: ExternalApprovalDecision | null;
  evidence?: ExternalApprovalEvidence[];
  expiresAt: string | null;
  createdAt: string;
}

export type ExternalApprovalTerminalResponse = ExternalApprovalStatusResponse & {
  status: ExternalApprovalTerminalStatus;
};

interface DataEnvelope<T> {
  data: T;
}

export type ExternalApprovalStatusEnvelope = DataEnvelope<ExternalApprovalStatusResponse>;
export type ExternalApprovalEvidenceEnvelope = DataEnvelope<ExternalApprovalEvidence>;

// ─── POST /v1/verify-token ───────────────────────────────────────────────────

/** Request body for POST /v1/verify-token */
export interface VerifyTokenRequest {
  /** The approval ID returned in the 201 response from POST /v1/intent. */
  approvalId: string;
  /**
   * The one-time token from the SSE `approval.approved` event or from
   * GET /v1/approvals/:id/status.
   */
  token: string;
}

/**
 * Response from POST /v1/verify-token on success (HTTP 200).
 *
 * After receiving this response, the SDK:
 * 1. Re-derives the gate key using HKDF(masterSecret, context.gateNonce)
 * 2. Decrypts local ciphertext
 * 3. Recomputes SHA-256(JSON.stringify(decryptedArgs))
 * 4. Asserts recomputed hash === context.payloadHash (tamper check)
 * 5. Calls fn() with decrypted args
 *
 * Phone-home is non-negotiable: fn() is NEVER called without a 200 from here.
 */
export interface VerifyTokenResponse {
  verified: true;
  context: {
    /** The approval ID that was verified. */
    approvalId: string;
    /** The intent name associated with this approval. */
    intent: string | null;
    /** The human user who approved (display name or email). */
    approvedBy: string | null;
    /**
     * base64(SHA-256(JSON.stringify(originalArgs))) — the hash the cloud
     * stored when the intent was registered. SDK compares this against its
     * recomputed hash of the decrypted args.
     */
    payloadHash: string | null;
    /**
     * The gateNonce used to derive the AES-256-GCM key for this gate.
     * Returned here (not in GET /v1/approvals/:id/status) as the authoritative
     * source for key re-derivation after phone-home.
     */
    gateNonce: string | null;
    /** ISO-8601 timestamp of when the approval was verified. */
    resolvedAt: string | null;
  };
}

// ─── SSE Events ──────────────────────────────────────────────────────────────

/**
 * A parsed event from the GET /v1/events/stream SSE endpoint.
 *
 * The SDK asks the stream for terminal approval events and still filters
 * client-side by approvalId. Only `approval.approved` events where
 * `entityId === approvalId` trigger the verify-token flow. All other events
 * are discarded.
 */
export interface SseEvent {
  /** Event type, e.g. `'approval.approved'`, `'approval.rejected'`, `'approval.expired'` */
  type: string;
  /** The ID of the entity this event pertains to (the approvalId for approval events). */
  entityId: string;
  /** Event-specific payload. Structure varies by event type. */
  payload: unknown;
}

/**
 * Payload shape for `approval.approved` SSE events.
 * The `token` field is the one-time token passed to verify-token.
 */
export interface ApprovalApprovedPayload {
  token: string;
}
