/**
 * Isomorphic cryptographic primitives for @meshgate/sdk.
 *
 * SECURITY CONSTRAINTS:
 * - Uses ONLY globalThis.crypto.subtle (Web Crypto API).
 * - NO imports from node:crypto. This file must work in Node.js 18+,
 *   Cloudflare Workers, Vercel Edge Runtime, Deno, and Bun.
 * - MESHGATE_LOCAL_SECRET (masterSecret) must never appear in logs, errors,
 *   or any serialized form. The derived CryptoKey is non-extractable.
 * - gateNonce is never stored locally — it is held by the Meshgate cloud and
 *   returned only on a successful POST /v1/verify-token (split-knowledge).
 */

import type { GatePayload } from '../types.js';
import { base64Decode, base64Encode, base64urlDecode, base64urlEncode } from './base64.js';

const subtle = globalThis.crypto.subtle;

// Pre-encode info bytes once. Cast through ArrayBuffer to satisfy TypeScript 5.5+'s
// stricter Uint8Array<ArrayBufferLike> vs Uint8Array<ArrayBuffer> distinction.
const HKDF_INFO: Uint8Array<ArrayBuffer> = (() => {
  const raw = new TextEncoder().encode('meshgate-v1');
  const buf = new ArrayBuffer(raw.length);
  new Uint8Array(buf).set(raw);
  return new Uint8Array(buf);
})();

// ─── gateNonce ───────────────────────────────────────────────────────────────

/**
 * Generate a cryptographically random gateNonce.
 *
 * 32 bytes → base64url-encoded (no padding).
 * Generated by guard() immediately before POST /v1/intent.
 * Sent to the cloud in the request body; never stored locally.
 */
export function generateGateNonce(): string {
  const buf = new ArrayBuffer(32);
  const bytes = new Uint8Array(buf);
  globalThis.crypto.getRandomValues(bytes);
  return base64urlEncode(bytes);
}

// ─── Key Derivation ──────────────────────────────────────────────────────────

/**
 * Derive a per-gate AES-256-GCM key via HKDF-SHA256.
 *
 * Parameters:
 *   ikm:    UTF-8 bytes of MESHGATE_LOCAL_SECRET
 *   salt:   base64url-decoded gateNonce (32 bytes)
 *   info:   UTF-8 bytes of "meshgate-v1"
 *   length: 32 bytes → 256-bit AES-GCM key
 *
 * The returned CryptoKey is non-extractable. Never persisted.
 * Re-derivable from the same (masterSecret, gateNonce) pair.
 */
export async function deriveGateKey(masterSecret: string, gateNonce: string): Promise<CryptoKey> {
  const masterRaw = new TextEncoder().encode(masterSecret);
  const masterBuf = new ArrayBuffer(masterRaw.length);
  new Uint8Array(masterBuf).set(masterRaw);

  const nonceBytes = base64urlDecode(gateNonce);

  const ikm = await subtle.importKey('raw', masterBuf, 'HKDF', false, ['deriveKey']);

  return subtle.deriveKey(
    { name: 'HKDF', hash: 'SHA-256', salt: nonceBytes, info: HKDF_INFO },
    ikm,
    { name: 'AES-GCM', length: 256 },
    false, // non-extractable
    ['encrypt', 'decrypt'],
  );
}

// ─── AES-256-GCM Encryption ──────────────────────────────────────────────────

/**
 * Encrypt a GatePayload with AES-256-GCM.
 *
 * Uses a fresh random 12-byte IV per encryption call (Web Crypto recommendation).
 * The Web Crypto API appends the 16-byte auth tag to the ciphertext output;
 * this function splits them into separate base64-encoded strings for storage.
 *
 * Returns { iv, authTag, ciphertext } — all base64-encoded (not base64url).
 */
export async function encryptGatePayload(
  key: CryptoKey,
  payload: GatePayload,
): Promise<{ iv: string; authTag: string; ciphertext: string }> {
  const ivBuf = new ArrayBuffer(12);
  const iv = new Uint8Array(ivBuf);
  globalThis.crypto.getRandomValues(iv);

  const plainRaw = new TextEncoder().encode(JSON.stringify(payload));
  const plainBuf = new ArrayBuffer(plainRaw.length);
  new Uint8Array(plainBuf).set(plainRaw);

  // AES-GCM output layout: [ciphertext bytes][16-byte auth tag]
  const combined = await subtle.encrypt({ name: 'AES-GCM', iv }, key, plainBuf);
  const bytes = new Uint8Array(combined);
  const ciphertext = bytes.slice(0, -16);
  const authTag = bytes.slice(-16);

  return {
    iv: base64Encode(iv),
    authTag: base64Encode(authTag),
    ciphertext: base64Encode(ciphertext),
  };
}

/**
 * Decrypt a GatePayload encrypted with AES-256-GCM.
 *
 * Web Crypto expects ciphertext + authTag concatenated for decryption.
 * Throws a DOMException (OperationError) if the auth tag is invalid —
 * this happens when the ciphertext was tampered with.
 *
 * SECURITY: Any exception from this function indicates tampered ciphertext.
 * The caller must re-raise it as MeshgateTamperError and must NOT call fn().
 */
export async function decryptGatePayload(
  key: CryptoKey,
  iv: string,
  authTag: string,
  ciphertext: string,
): Promise<GatePayload> {
  const ivBytes = base64Decode(iv);
  const authTagBytes = base64Decode(authTag);
  const ciphertextBytes = base64Decode(ciphertext);

  // WebCrypto decrypt expects [ciphertext][authTag] concatenated
  const combinedBuf = new ArrayBuffer(ciphertextBytes.length + authTagBytes.length);
  const combined = new Uint8Array(combinedBuf);
  combined.set(ciphertextBytes);
  combined.set(authTagBytes, ciphertextBytes.length);

  const plaintext = await subtle.decrypt({ name: 'AES-GCM', iv: ivBytes }, key, combined);

  return JSON.parse(new TextDecoder().decode(plaintext)) as GatePayload;
}

// ─── payloadHash ─────────────────────────────────────────────────────────────

/**
 * Compute the payload hash for tamper detection.
 *
 * payloadHash = base64(SHA-256(JSON.stringify(args)))
 *
 * Sent to the cloud in POST /v1/intent. Returned by the cloud in
 * POST /v1/verify-token as context.payloadHash. The SDK recomputes this
 * after decryption and compares — mismatch throws MeshgateTamperError.
 *
 * Uses standard base64 (not base64url) to match the cloud's encoding.
 *
 * PRECONDITION: args must be JSON-serializable. If JSON.stringify throws,
 * the caller (guard()) must catch it and throw MeshgateSerializationError
 * before any network calls are made.
 */
export async function computePayloadHash(args: unknown[]): Promise<string> {
  const json = JSON.stringify(args);
  const raw = new TextEncoder().encode(json);
  const buf = new ArrayBuffer(raw.length);
  new Uint8Array(buf).set(raw);
  const hash = await subtle.digest('SHA-256', buf);
  return base64Encode(new Uint8Array(hash));
}
